spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exampledb   # 데이터베이스 URL
    username: root                     # 데이터베이스 사용자 이름
    password: u1234
                                                   # 데이터베이스 암호


  jpa:
    hibernate:
      ddl-auto: update                             # Hibernate DDL 자동 생성 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # 데이터베이스 방언 설정 (MySQL 8 사용 예시)