spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useUnicode=true&serverTimezone=Asia/Seoul   # 데이터베이스 URL
    username: root                     # 데이터베이스 사용자 이름
    password: u1234
                                                   # 데이터베이스 암호


  jpa:
    hibernate:
      ddl-auto: update                             # Hibernate DDL 자동 생성 설정
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
